### ISSUE TITLE
Next release

### ISSUE THREAD

**Issue by bzuidgeest** [giessweinapps/MonoDebugger#44]
I registered my email on http://www.monodebugger.net/ last year. The site says there would be a release in 2015, but I never saw it. I would like to know if there is any progress? Seems such an interesting product/tool

**Comment by endricott** [comment]
2016-03-30 20:42:27.0529|ERROR|MonoDebugger.VS2013.MonoDebuggerPackage|System.Net.Sockets.SocketException (0x80004005): No connection could be made because the target machine actively refused it 127.0.0.1:13001
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MonoDebugger.VS2013.MonoClient.DebugClient.<ConnectToServerAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MonoDebugger.VS2013.MonoVisualStudioExtension.<AttachDebugger>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MonoDebugger.VS2013.MonoDebuggerPackage.<StartSearching>d__8.MoveNext()
2016-03-30 20:43:15.7323|INFO|MonoDebugger.SharedLib.Server.MonoDebugServer|Closed MonoDebugServer
2016-03-30 20:43:15.8712|INFO|MonoDebugger.SharedLib.Server.MonoDebugServer|Waiting for client
2016-03-30 20:43:15.8712|INFO|MonoDebugger.SharedLib.Server.MonoDebugServer|Accepted client: 192.168.1.17:51700
2016-03-30 20:43:16.0700|ERROR|MonoDebugger.VS2013.MonoDebuggerPackage|System.AggregateException: One or more errors occurred. ---> System.UnauthorizedAccessException: Access to the path 'MonoDebugger' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at System.IO.Directory.CreateDirectory(String path)
   at MonoDebugger.SharedLib.Server.ClientSession..ctor(Socket socket)
   at MonoDebugger.SharedLib.Server.MonoDebugServer.StartListening(CancellationToken token)
   at MonoDebugger.SharedLib.Server.MonoDebugServer.<Start>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at MonoDebugger.SharedLib.Server.MonoDebugServer.Stop()
   at MonoDebugger.SharedLib.Server.MonoDebugServer.Dispose()
   at MonoDebugger.VS2013.MonoDebuggerPackage.<StartLocalServer>d__4.MoveNext()
---> (Inner Exception #0) System.UnauthorizedAccessException: Access to the path 'MonoDebugger' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at System.IO.Directory.CreateDirectory(String path)
   at MonoDebugger.SharedLib.Server.ClientSession..ctor(Socket socket)
   at MonoDebugger.SharedLib.Server.MonoDebugServer.StartListening(CancellationToken token)
   at MonoDebugger.SharedLib.Server.MonoDebugServer.<Start>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---
 



connected ip .17 i tried local and it crashes vs2013
